global:
  http:
    listen_addr: ":12079"
#    listen_addr_tls: ":12080" # 用于HTTPS方式访问API的端口配置
#    cert_file: "go-jt808.online.crt"
#    key_file: "go-jt808.online.key"
  tcp:
    listen_addr: ":12081"

jt1078:
  enable: true

  intercom:
    enable: false # 是否启用 用于双向对讲
    jt1078webrtc:
      port: 12020 # 对讲默认udp端口
      ip: "124.221.30.46" # 外网ip 用于SDP协商修改
    audio_ports: [12021, 12050] # 音频端口范围 [min,max]
    on_join_url: "https://127.0.0.1:12000/api/v1/jt808/event/join-audio" # 设备连接到音频端口的回调
    on_leave_url: "https://127.0.0.1:12000/api/v1/jt808/event/leave-audio" # 设备断开了音频端口的回调
    overtime_second: 60 # 多久没有下发对讲语言的数据 就关闭这个链接

  realtime: # 实时视频
    addr: '0.0.0.0:12051'
    on_join_url: "https://127.0.0.1:12000/api/v1/jt808/event/real-time-join"
    on_leave_url: "https://127.0.0.1:12000/api/v1/jt808/event/real-time-leave"
    prefix: "live/jt1078" # 默认自定义前缀-手机号-通道 如：live/jt1078-295696659617-1

  playback: # 回放视频
    addr: '0.0.0.0:12052'
    on_join_url: "https://127.0.0.1:12000/api/v1/play-back-join"
    on_leave_url: "https://127.0.0.1:12000/api/v1/play-back-leave"
    prefix: "live/jt1079" # 默认自定义前缀-手机号-通道 如：live/jt1079-295696659617-1

  simulations:
    # jt1078文件 默认循环发送
    - name: ../testdata/data.txt
      addr: 127.0.0.1:12051 # 模拟实时
    - name: ../testdata/audio_data.txt
      addr: 127.0.0.1:12052 # 模拟回放

mp4:
  enable: true
